### ISSUE TITLE
Version Number & Check

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/Flotilla-Daemon-VS#1]
A version number should be baked into the Flotilla Daemon and checked at runtime by Rockpool to ensure that all parts of the system are matched and likely to function properly together.

**Comment by RogueM** [comment]
I believe this can be closed?

**Comment by RogueM** [comment]
incidentally I have bumped the daemon version to 1.13 when building for macosx as 1.12 did not contain the latest change, well, I don't think it did.
